/**
 * code for menu
 */

document.write('<div class="main_menu"><ul class="main_nav"><li><a href="javascript:void(0)" target="_parent" title="Главная">главная</a></li><li><a href="javascript:void(0)" target="_parent" title="Главная">О компании</a></li><li><a href="javascript:void(0)" target="_parent" title="Хиты продаж">хиты продаж</a></li><li><a href="javascript:void(0)" target="_parent" title="Акции и скидки">акции и скидки</a></li><li><a href="javascript:void(0)" target="_parent" title="Калькулятор">калькулятор</a></li><li><a href="javascript:void(0)" target="_parent" title="Консультация">консультация</a></li></ul></div>');

document.write('<div class="main-menu-mobile"><ul class="main-nav-mobile"><li><a href="javascript:void(0)" target="_parent" title="Главная">главная</a><a href="javascript:void(0)" target="_parent" title="Главная">О компании</a></li><li><a href="javascript:void(0)" target="_parent" title="Хиты продаж">хиты продаж</a><a href="javascript:void(0)" target="_parent" title="Акции и скидки">акции и скидки</a></li><li><a href="javascript:void(0)" target="_parent" title="Калькулятор">калькулятор</a><a href="javascript:void(0)" target="_parent" title="Консультация">консультация</a></li></ul></div>');

document.write('<div class="main-menu-mobile460"><ul class="main-nav-mobile460"><li><a href="javascript:void(0)" target="_parent" title="Главная">главная</a><a href="javascript:void(0)" target="_parent" title="Главная">О компании</a><a href="javascript:void(0)" target="_parent" title="Хиты продаж">хиты продаж</a></li><li><a href="javascript:void(0)" target="_parent" title="Акции и скидки">акции и скидки</a><a href="javascript:void(0)" target="_parent" title="Калькулятор">калькулятор</a><a href="javascript:void(0)" target="_parent" title="Консультация">консультация</a></li></ul></div>');

document.write('<div class="main-menu-mobile320"><ul class="buttontop"><li><a href="javascript:void(0)" title="Главная"><img src="images/home-pic.png"></a></li><li><a href="javascript:void(0)" title="Галерея наших работ"><img src="images/job-button.png"></a></li><li><a href="javascript:void(0)" title="Акции и скидки"><img src="images/money5.gif"></a></li><li><a href="javascript:void(0)" title="Отзывы"><img src="images/otziv-button.png"></a></li><li><a href="javascript:void(0)" title="Контакты"><img src="images/contact-button.png"></a></li></ul><ul class="nav nav-pills"><li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">О компании<span class="caret"></span></a><ul class="dropdown-menu"><li><a href="javascript:void(0)" title="Галерея наших работ">Галерея наших работ</a></li><li><a href="javascript:void(0)" title="Почему Командор">Почему Командор?</a></li><li><a href="javascript:void(0)" title="Ролик Командор">Ролик Командор</a></li><li><a href="javascript:void(0)" title="Кредит">Кредит 0%</a></li><li><a href="javascript:void(0)" title="Рассрочка">Рассрочка 0%</a></li><li> <a href="javascript:void(0)" title="Консультация">Консультация</a></li><li><a href="javascript:void(0)" title="Гарантии">Гарантии</a></li><li><a href="javascript:void(0)" title="Дилерский отдел">Дилерский отдел</a></li><li><a href="javascript:void(0)" title="Калькулятор">Калькулятор</a></li><li><a href="javascript:void(0)" title="Архив">Архив</a></li></ul></li><li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Шкафы-купе<span class="caret"></span></a><ul class="dropdown-menu"><li><a href="javascript:void(0)" title="Хиты Продаж">Хиты Продаж</a></li><li><a href="javascript:void(0)" title="Акции и скидки">Акции и скидки</a></li><li><a href="standart.html" title="Стандартные">Стандартные</a></li><li><a href="javascript:void(0)" title="На заказ">На заказ</a></li><li> <a href="javascript:void(0)" title="Угловые">Угловые</a></li><li><a href="javascript:void(0)" title="Встроенные">Встроенные</a></li><li><a href="javascript:void(0)" title="Всё о шкафах-купе">Всё о шкафах-купе!</a></li></ul></li><li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Состав<span class="caret"></span></a><ul class="dropdown-menu"><li><a href="javascript:void(0)" title="Материалы">Материалы</a></li><li><a href="javascript:void(0)" title="Пескоструйные рисунки">Пескоструйные рисунки</a></li><li><a href="vitraj.html" title="Витражи">Витражи</a></li><li><a href="javascript:void(0)" title="Фотопечать">Фотопечать</a></li><li> <a href="javascript:void(0)" title="Акриловые панели">Акриловые панели</a></li><li><a href="javascript:void(0)" title="Зеркала и стекла">Зеркала и стекла</a></li></ul></li></ul></div>');